#Wap to read two int inputs and perform arithmetic operations
a=int(input("Enter num1: "))
b=int(input("Enter num2: "))
print("Addition of {} and {} = ".format(a,b),a+b)
print("Subtraction of {} and {} = ".format(a,b),a-b)
print("Multiplication of {} and {} = ".format(a,b),a*b)
print("Division of {} and {} = ".format(a,b),a/b)
print("Floor Division of {} and {} = ".format(a,b),a//b)
print("Modulus of {} and {} = ".format(a,b),a%b)
print("Power of {} and {} = ".format(a,b),a**b)