x=int(input("Enter an integer value: "))
y=int(input("Enter an integer value: "))
print(x,"<<",y,"is",x<<y)
print(x,">>",y,"is",x>>y)
print(x,"AND",y,"is",x&y)
print(x,"OR",y,"is",x|y)
print(x,"^",y,"is",x^y)
print("~",y,"is",~y)